const players = [
	{
		id: "michael-jordan",
		name: "Michael Jordan",
		team: "Chicago Bulls",
		points: 32292,
		assists: 5633,
		rebounds: 6672,
		steals: 2514,
		blocks: 893,
		nbaTitles: 6,
		mvpTitles: 5,
		image: "michael-jordan.jpg",
	},
	{
		id: "hakeem-olajuwon",
		name: "Hakeem Olajuwon",
		team: "Houston Rockets",
		points: 26946,
		assists: 3058,
		rebounds: 13748,
		steals: 2162,
		blocks: 3830,
		nbaTitles: 2,
		mvpTitles: 1,
		image: "hakeem-olajuwon.jpg",
	},
	{
		id: "kobe-bryant",
		name: "Kobe Bryant",
		team: "Los Angeles Lakers",
		points: 33643,
		assists: 6306,
		rebounds: 7047,
		steals: 1944,
		blocks: 640,
		nbaTitles: 5,
		mvpTitles: 1,
		image: "kobe-bryant.jpg",
	},
];

module.exports = players;
